using UnityEngine;

namespace DungeonDash
{
    public static class CreditsPanel
    {
        public static RectTransform Show(Transform parent)
        {
            var root = UiKit.Node("Credits", parent);
            UiKit.Stretch(root, 0f, 0f, 0f, 0f);
            UiKit.Shade("Shade", root, UiPalette.Ink.Alpha(0.96f));
            var dialog = UiKit.Dialog(root, "CREDITS", "THE PEOPLE AND TOOLS BEHIND THE DUNGEON",
                UiPalette.Gold, 800f, 620f);
            var close = UiKit.PushButton("Close", dialog.HeaderActions, "CLOSE", ButtonTone.Ghost,
                () => Object.Destroy(root.gameObject), 14);
            UiKit.Corner(close.Rect, new Vector2(1f, 0.5f), Vector2.zero, new Vector2(120f, 42f));

            var scroll = UiKit.ScrollList("Notices", dialog.Body, out var content);
            UiKit.Stretch((RectTransform)scroll.transform, 0f, 0f, 0f, 0f);
            string credits = "PIXEL ART\nDungeon Tileset II by 0x72 (Robert) · CC0\n" +
                "0x72.itch.io/dungeontileset-ii\n\n" +
                "FONTS\nVT323 by Peter Hull\nPress Start 2P by CodeMan38\n" +
                "Both fonts are distributed under the SIL Open Font License 1.1.\n\n" +
                "MADE WITH UNITY\nSound effects and ground tiles are generated by the project's tools.\n" +
                "The app icon was created with OpenAI image generation.\n\n" +
                "FONT LICENSE NOTICES\n\n" +
                Resources.Load<TextAsset>("Fonts/OFL-VT323").text + "\n\n" +
                Resources.Load<TextAsset>("Fonts/OFL-PressStart2P").text;
            var text = UiKit.Wrapped("Text", content, credits, 22, UiPalette.Cream);
            UiKit.Place(text.rectTransform, 14f, 12f, 720f, 1f);
            float height = text.preferredHeight;
            text.rectTransform.sizeDelta = new Vector2(720f, height);
            UiKit.SetContentHeight(content, height + 24f);
            return root;
        }
    }
}
