using System.Collections.Generic;
using UnityEngine;

namespace DungeonDash
{
    // Pooled retro SFX player + ambience loop. Auto-boots like the other DungeonDash
    // systems (GameFeel, PixelBurst) so callers just use the static Play API. Clips are
    // generated by Tools/generate_sfx.py into Resources/Audio and loaded by id on Awake.
    public sealed class GameAudio : MonoBehaviour
    {
        const int PoolSize = 8;
        const float PitchJitter = 0.06f;
        const float CoalesceWindow = 0.03f;
        const float AmbienceVolume = 0.25f;
        const float MasterVolume = 1f;
        const string VolumePreferenceKey = "DungeonDash.AudioVolume";

        public const int MaxVolumeStep = 4;
        public static bool MutedForAutomation { get; } = Application.isBatchMode ||
            System.Array.Exists(System.Environment.GetCommandLineArgs(), argument =>
                argument.StartsWith("--qa-", System.StringComparison.Ordinal));
        public static int SavedVolumeStep =>
            Mathf.Clamp(PlayerPrefs.GetInt(VolumePreferenceKey, MaxVolumeStep), 0, MaxVolumeStep);

        static readonly string[] ClipIds =
        {
            "swing_whoosh", "bow_shot", "hit_impact", "crit_impact", "enemy_die",
            "player_hurt", "coin", "potion", "chest_open", "bomb_explode",
            "dash_whoosh", "ui_click", "ui_hover_soft", "wave_start", "game_over",
            "artifact_drop"
        };

        static GameAudio _instance;

        readonly Dictionary<string, AudioClip> _clips = new();
        readonly Dictionary<string, float> _lastPlayed = new();
        AudioSource[] _pool;
        int _poolCursor;

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
        static void Boot()
        {
            if (FindFirstObjectByType<GameAudio>() == null)
                new GameObject("Game Audio").AddComponent<GameAudio>();
        }

        void Awake()
        {
            _instance = this;
            ApplySavedVolume();
            if (MutedForAutomation)
            {
                Debug.Log("[DungeonDash] Automated audio muted.");
                return;
            }

            foreach (var id in ClipIds)
            {
                var clip = Resources.Load<AudioClip>("Audio/" + id);
                if (clip != null) _clips[id] = clip;
            }

            _pool = new AudioSource[PoolSize];
            for (int i = 0; i < PoolSize; i++)
            {
                var source = gameObject.AddComponent<AudioSource>();
                source.playOnAwake = false;
                source.spatialBlend = 0f;
                _pool[i] = source;
            }

            var ambienceClip = Resources.Load<AudioClip>("Audio/dungeon_ambience");
            if (ambienceClip != null)
            {
                var ambience = gameObject.AddComponent<AudioSource>();
                ambience.clip = ambienceClip;
                ambience.loop = true;
                ambience.playOnAwake = false;
                ambience.spatialBlend = 0f;
                ambience.volume = AmbienceVolume;
                ambience.Play();
            }
        }

        public static void Play(string id, float volume = 1f)
        {
            if (_instance == null || MutedForAutomation) return;
            _instance.PlayInternal(id, volume);
        }

        public static void SetVolumeStep(int step)
        {
            PlayerPrefs.SetInt(VolumePreferenceKey, Mathf.Clamp(step, 0, MaxVolumeStep));
            PlayerPrefs.Save();
            ApplySavedVolume();
        }

        public static void ApplySavedVolume()
        {
            AudioListener.volume = MutedForAutomation ? 0f : SavedVolumeStep / (float)MaxVolumeStep;
        }

        void PlayInternal(string id, float volume)
        {
            if (!_clips.TryGetValue(id, out var clip)) return;
            if (_lastPlayed.TryGetValue(id, out float last) && Time.unscaledTime - last < CoalesceWindow) return;
            _lastPlayed[id] = Time.unscaledTime;

            var source = _pool[_poolCursor];
            _poolCursor = (_poolCursor + 1) % _pool.Length;
            source.pitch = id.StartsWith("ui_", System.StringComparison.Ordinal)
                ? 1f
                : 1f + Random.Range(-PitchJitter, PitchJitter);
            source.PlayOneShot(clip, volume * MasterVolume);
        }
    }
}
